---

rules:
  class-name-format:
    - 1
    -
      convention: '\-?[a-z0-9][a-zA-Z0-9]+([\-\_][a-z0-9][a-zA-Z0-9]+)*'
      convention-explanation: Lower camel case with underscore or hyphens separation according to BEM
